name: website-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    infrastrucutre-directory: infrastrucutre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          extended: true
          
      - name: Terraform init
        run : |
          cd infrastructure
          make init

      - name: Terraform validate
        run : |
          cd infrastructure
          make validate
      
      - name: Terraform lint
        run : |
          cd infrastructure
          make lint
      
      - name: Terraform plan and apply
        run : |
          cd infrastructure
          make plan
          make apply
